-- Add sample feedback responses for testing
INSERT INTO feedback_responses (user_name, user_email, bootcamp_id, session_id, responses, submitted_at) VALUES
('Rahul Sharma', 'rahul.sharma@email.com', 'BC2024001', 
 (SELECT id FROM feedback_sessions WHERE title = 'Speed Math Workshop' LIMIT 1),
 '{"rating_1": "5", "feedback_1": "Excellent workshop! The techniques really helped improve my calculation speed.", "location_1": "Pune"}',
 '2024-01-15 10:30:00'),
('Priya Patel', 'priya.patel@email.com', 'BC2024002',
 (SELECT id FROM feedback_sessions WHERE title = 'Gen AI Workshop' LIMIT 1),
 '{"rating_1": "4", "feedback_1": "Great content on AI fundamentals. Would love more hands-on exercises.", "location_1": "Hyderabad"}',
 '2024-01-15 14:20:00'),
('Amit Kumar', 'amit.kumar@email.com', 'BC2024003',
 (SELECT id FROM feedback_sessions WHERE title = 'Personal Branding Workshop' LIMIT 1),
 '{"rating_1": "5", "feedback_1": "Very insightful session on building professional brand online.", "location_1": "Noida"}',
 '2024-01-16 09:15:00'),
('Sneha Reddy', 'sneha.reddy@email.com', 'BC2024004',
 (SELECT id FROM feedback_sessions WHERE title = 'LinkedIn Workshop' LIMIT 1),
 '{"rating_1": "4", "feedback_1": "Learned valuable LinkedIn optimization strategies.", "location_1": "Hyderabad"}',
 '2024-01-16 16:45:00'),
('Vikash Singh', 'vikash.singh@email.com', 'BC2024005',
 (SELECT id FROM feedback_sessions WHERE title = 'IOT Workshop' LIMIT 1),
 '{"rating_1": "5", "feedback_1": "Amazing hands-on experience with IoT devices and programming.", "location_1": "Pune"}',
 '2024-01-17 11:30:00'),
('Deepika Agarwal', 'deepika.agarwal@email.com', 'BC2024006',
 (SELECT id FROM feedback_sessions WHERE title = 'Drone Workshop' LIMIT 1),
 '{"rating_1": "4", "feedback_1": "Exciting workshop on drone technology and applications.", "location_1": "Noida"}',
 '2024-01-17 15:20:00'),
('Ravi Gupta', 'ravi.gupta@email.com', 'BC2024007',
 (SELECT id FROM feedback_sessions WHERE title = 'Kaizen Workshop' LIMIT 1),
 '{"rating_1": "5", "feedback_1": "Excellent concepts on continuous improvement methodology.", "location_1": "Pune"}',
 '2024-01-18 10:00:00'),
('Ankita Joshi', 'ankita.joshi@email.com', 'BC2024008',
 (SELECT id FROM feedback_sessions WHERE title = 'Community Building Session' LIMIT 1),
 '{"rating_1": "4", "feedback_1": "Great strategies for building and engaging communities.", "location_1": "Hyderabad"}',
 '2024-01-18 14:30:00'),
('Suresh Nair', 'suresh.nair@email.com', 'BC2024009',
 (SELECT id FROM feedback_sessions WHERE title = 'Tribe Huddle Session' LIMIT 1),
 '{"rating_1": "5", "feedback_1": "Fantastic networking and collaboration session.", "location_1": "Noida"}',
 '2024-01-19 09:45:00'),
('Kavya Menon', 'kavya.menon@email.com', 'BC2024010',
 (SELECT id FROM feedback_sessions WHERE title = 'Tribeathon Event' LIMIT 1),
 '{"rating_1": "5", "feedback_1": "Outstanding event with great team challenges and learning.", "location_1": "Pune"}',
 '2024-01-19 18:00:00');