// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjvsgediksvdhxumadak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdnNnZWRpa3N2ZGh4dW1hZGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzI3NDcsImV4cCI6MjA2Njc0ODc0N30.YfbZOQcSo29qQt-xO6TXRL8SFoUEf3mN3K4JEfJKyzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});